### ISSUE TITLE
Bug in TensorFlow

### ISSUE THREAD

**Issue by dafnasadeh** [pponnada/segmentseq2seq#1]
When I try to run predict.py I get the following error in TensorFlow seq2seq.
Does someone know how to fix it?

Thanks!
 
Traceback (most recent call last):
  File "/root/segmentseq2seq/predict.py", line 55, in <module>
    num_layers=num_layers)
  File "/root/segmentseq2seq/model.py", line 72, in __init__
    self.enc_ip, self.dec_ip, stacked_lstm, xvocab_size, yvocab_size, emb_dim, feed_previous=True)
  File "/root/tensorflow/local/lib/python3.4/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 358, in embedding_rnn_seq2seq
    encoder_cell = copy.deepcopy(cell)
  File "/root/tensorflow/lib/python3.4/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "/root/tensorflow/local/lib/python3.4/site-packages/tensorflow/python/layers/base.py", line 487, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 219, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/root/tensorflow/lib/python3.4/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "/root/tensorflow/local/lib/python3.4/site-packages/tensorflow/python/layers/base.py", line 487, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/root/tensorflow/lib/python3.4/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "/root/tensorflow/local/lib/python3.4/site-packages/tensorflow/python/layers/base.py", line 487, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 219, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/root/tensorflow/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 219, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/root/tensorflow/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 219, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 226, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/root/tensorflow/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/root/tensorflow/lib/python3.4/copy.py", line 309, in _reconstruct
    y.__dict__.update(state)
AttributeError: 'NoneType' object has no attribute 'update'

**Comment by pponnada** [comment]
I haven't been actively maintaining this project. Can you try to see what changed in Tensorflow wrt seq2seq between versions used by me and the ones used by you? That should hopefully fix the issue with encoder_cel
